name: AliStraightsound
favicon: null
layout_spectrum: null
typography_spectrum: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#25414d'
    - '#90a55a'
    - '#5c6634'
  brandStrength: 1
  lightness: null
  saturation: null
  rhythmicContrast: null
purpose: []
