name: AliStraightsound
favicon: null
layout_spectrum: 0.1481
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0608'
    - '#1e0f0c'
    - '#482924'
    - '#d75e01'
    - '#282222'
  brandStrength: 0
  lightness: 0
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
