favicon: null
name: AliStraightsound
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: null
  brandStrength: 1
  lightness: null
  brandColors:
    - '#2B2B2B'
    - '#ECE3D2'
    - '#97ACBD'
    - '#787969'
    - '#6593B5'
  rhythmicContrast: null
typography_spectrum: 0.5663083
layout_spectrum: 0.5053763
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
